package com.yizhaoqi.smartpai.service;

import com.yizhaoqi.smartpai.model.ToolResult;
import com.yizhaoqi.smartpai.tools.Tool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * 工具执行器
 * 负责执行工具调用，包含权限验证、参数验证、异常处理等
 * 
 * @author Generated by AI Assistant
 */
@Service
public class ToolExecutor {

    private static final Logger logger = LoggerFactory.getLogger(ToolExecutor.class);

    @Autowired
    private ToolRegistry toolRegistry;

    /**
     * 执行工具
     * 
     * @param toolName   工具名称
     * @param parameters 工具参数
     * @param userId     调用用户ID
     * @return 执行结果
     */
    public ToolResult executeTool(String toolName, Map<String, Object> parameters, String userId) {
        long startTime = System.currentTimeMillis();

        try {
            logger.info("开始执行工具: {}, 用户: {}, 参数: {}", toolName, userId, parameters);

            // 1. 检查工具是否存在
            if (!toolRegistry.hasTool(toolName)) {
                logger.error("工具不存在: {}", toolName);
                return ToolResult.failure("工具不存在: " + toolName);
            }

            // 2. 获取工具实例
            Tool tool = toolRegistry.getTool(toolName);

            // 3. 验证参数（简化版，实际应该根据 JSON Schema 验证）
            if (parameters == null) {
                parameters = Map.of();
            }

            // 4. 执行工具
            ToolResult result = tool.execute(parameters, userId);

            long executionTime = System.currentTimeMillis() - startTime;
            logger.info("工具执行完成: {}, 耗时: {}ms, 成功: {}",
                    toolName, executionTime, result.isSuccess());

            return result;

        } catch (Exception e) {
            long executionTime = System.currentTimeMillis() - startTime;
            logger.error("工具执行异常: {}, 耗时: {}ms", toolName, executionTime, e);
            return ToolResult.failure("工具执行异常: " + e.getMessage(), executionTime);
        }
    }
}
