package com.yizhaoqi.smartpai.service;

import com.yizhaoqi.smartpai.model.ToolDefinition;
import com.yizhaoqi.smartpai.tools.Tool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import java.util.*;

/**
 * 工具注册中心
 * 负责管理所有可用的 Function Call 工具
 * 
 * @author Generated by AI Assistant
 */
@Service
public class ToolRegistry {

    private static final Logger logger = LoggerFactory.getLogger(ToolRegistry.class);

    private final Map<String, Tool> tools = new LinkedHashMap<>();

    @Autowired(required = false)
    private List<Tool> availableTools;

    /**
     * 初始化：自动注册所有 Tool 实现
     */
    @PostConstruct
    public void init() {
        if (availableTools != null) {
            for (Tool tool : availableTools) {
                registerTool(tool);
            }
            logger.info("工具注册完成，共注册 {} 个工具: {}",
                    tools.size(), tools.keySet());
        } else {
            logger.warn("未找到任何可用工具");
        }
    }

    /**
     * 注册工具
     */
    public void registerTool(Tool tool) {
        String toolName = tool.getName();
        tools.put(toolName, tool);
        logger.info("注册工具: {}", toolName);
    }

    /**
     * 获取工具
     */
    public Tool getTool(String toolName) {
        return tools.get(toolName);
    }

    /**
     * 获取所有工具定义（用于发送给大模型）
     */
    public List<ToolDefinition> getAllToolDefinitions() {
        return tools.values().stream()
                .map(Tool::getDefinition)
                .toList();
    }

    /**
     * 获取所有工具名称
     */
    public Set<String> getAllToolNames() {
        return tools.keySet();
    }

    /**
     * 检查工具是否存在
     */
    public boolean hasTool(String toolName) {
        return tools.containsKey(toolName);
    }

    /**
     * 获取工具数量
     */
    public int getToolCount() {
        return tools.size();
    }
}
