package com.yizhaoqi.smartpai.tools;

import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.model.FileUpload;
import com.yizhaoqi.smartpai.model.ToolDefinition;
import com.yizhaoqi.smartpai.model.ToolDefinition.FunctionDefinition;
import com.yizhaoqi.smartpai.model.ToolDefinition.ParametersSchema;
import com.yizhaoqi.smartpai.model.ToolDefinition.PropertyDefinition;
import com.yizhaoqi.smartpai.model.ToolResult;
import com.yizhaoqi.smartpai.repository.FileUploadRepository;
import com.yizhaoqi.smartpai.service.HybridSearchService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 高级文档搜索工具
 * 支持按关键词、文件类型、组织标签、公开性、时间范围等多维度精准过滤
 * 
 * @author Generated by AI Assistant
 */
@Component
public class AdvancedDocumentSearchTool implements Tool {

    private static final Logger logger = LoggerFactory.getLogger(AdvancedDocumentSearchTool.class);

    @Autowired
    private HybridSearchService hybridSearchService;

    @Autowired
    private FileUploadRepository fileUploadRepository;

    @Override
    public ToolDefinition getDefinition() {
        // 定义参数
        Map<String, PropertyDefinition> properties = new LinkedHashMap<>();

        properties.put("keywords", PropertyDefinition.builder()
                .type("string")
                .description("搜索关键词，支持语义搜索")
                .build());

        properties.put("file_type", PropertyDefinition.builder()
                .type("string")
                .description("文件类型过滤，如 'pdf', 'docx', 'txt', 'xlsx', 'pptx' 等，不指定则搜索所有类型")
                .enumValues(Arrays.asList("pdf", "docx", "txt", "xlsx", "pptx", "md", "all"))
                .build());

        properties.put("org_tag", PropertyDefinition.builder()
                .type("string")
                .description("组织标签过滤，只搜索特定组织的文档")
                .build());

        properties.put("is_public", PropertyDefinition.builder()
                .type("boolean")
                .description("公开性过滤：true-只搜索公开文档，false-只搜索私有文档，不指定则搜索全部")
                .build());

        properties.put("date_from", PropertyDefinition.builder()
                .type("string")
                .description("开始日期过滤，格式 YYYY-MM-DD，搜索该日期之后上传的文档")
                .build());

        properties.put("date_to", PropertyDefinition.builder()
                .type("string")
                .description("结束日期过滤，格式 YYYY-MM-DD，搜索该日期之前上传的文档")
                .build());

        properties.put("top_k", PropertyDefinition.builder()
                .type("integer")
                .description("返回结果数量")
                .defaultValue(5)
                .build());

        return ToolDefinition.builder()
                .type("function")
                .function(FunctionDefinition.builder()
                        .name("advanced_document_search")
                        .description("高级文档搜索工具，支持按关键词、文件类型、组织标签、公开性、时间范围等多维度精准过滤。" +
                                "当用户需要查找特定类型、特定组织的文档，或需要时间范围过滤时使用此工具。")
                        .parameters(ParametersSchema.builder()
                                .type("object")
                                .properties(properties)
                                .required(Collections.singletonList("keywords"))
                                .build())
                        .build())
                .build();
    }

    @Override
    public ToolResult execute(Map<String, Object> parameters, String userId) {
        long startTime = System.currentTimeMillis();

        try {
            // 提取参数
            String keywords = (String) parameters.get("keywords");
            String fileType = (String) parameters.get("file_type");
            String orgTag = (String) parameters.get("org_tag");
            Boolean isPublic = (Boolean) parameters.get("is_public");
            String dateFrom = (String) parameters.get("date_from");
            String dateTo = (String) parameters.get("date_to");
            Integer topK = parameters.containsKey("top_k") ? ((Number) parameters.get("top_k")).intValue() : 5;

            logger.info(
                    "执行高级文档搜索 - userId: {}, keywords: {}, fileType: {}, orgTag: {}, isPublic: {}, dateFrom: {}, dateTo: {}, topK: {}",
                    userId, keywords, fileType, orgTag, isPublic, dateFrom, dateTo, topK);

            // 1. 先进行语义搜索（扩大范围以便后续过滤）
            List<SearchResult> searchResults = hybridSearchService
                    .searchWithPermission(keywords, userId, topK * 3);

            logger.info("语义搜索返回 {} 个结果", searchResults.size());

            // 2. 获取文档元数据并应用过滤条件
            List<Map<String, Object>> filteredResults = searchResults.stream()
                    .map(result -> {
                        Optional<FileUpload> fileOpt = fileUploadRepository.findByFileMd5(result.getFileMd5());
                        if (fileOpt.isEmpty()) {
                            return null;
                        }
                        return Map.of("searchResult", result, "fileUpload", fileOpt.get());
                    })
                    .filter(Objects::nonNull)
                    .filter(map -> matchesFilters(
                            (FileUpload) map.get("fileUpload"),
                            fileType, orgTag, isPublic, dateFrom, dateTo))
                    .limit(topK)
                    .map(map -> {
                        SearchResult sr = (SearchResult) map.get("searchResult");
                        FileUpload fu = (FileUpload) map.get("fileUpload");

                        Map<String, Object> resultMap = new LinkedHashMap<>();
                        resultMap.put("file_md5", sr.getFileMd5());
                        resultMap.put("file_name", sr.getFileName());
                        resultMap.put("chunk_text", sr.getChunkText());
                        resultMap.put("score", String.format("%.2f", sr.getScore()));
                        resultMap.put("file_size", formatFileSize(fu.getTotalSize()));
                        resultMap.put("upload_time", fu.getCreatedAt().toString());
                        resultMap.put("is_public", fu.isPublic());
                        resultMap.put("org_tag", fu.getOrgTag());

                        return resultMap;
                    })
                    .collect(Collectors.toList());

            long executionTime = System.currentTimeMillis() - startTime;

            logger.info("高级文档搜索完成 - 找到 {} 个符合条件的文档，耗时 {}ms",
                    filteredResults.size(), executionTime);

            // 返回结果
            Map<String, Object> response = new LinkedHashMap<>();
            response.put("total", filteredResults.size());
            response.put("documents", filteredResults);
            response.put("filters_applied", buildFiltersDescription(fileType, orgTag, isPublic, dateFrom, dateTo));

            return ToolResult.success(response, executionTime);

        } catch (Exception e) {
            long executionTime = System.currentTimeMillis() - startTime;
            logger.error("高级文档搜索失败", e);
            return ToolResult.failure("搜索失败: " + e.getMessage(), executionTime);
        }
    }

    /**
     * 检查文档是否匹配过滤条件
     */
    private boolean matchesFilters(FileUpload file, String fileType, String orgTag,
            Boolean isPublic, String dateFrom, String dateTo) {
        // 文件类型过滤
        if (fileType != null && !fileType.equals("all")) {
            String fileName = file.getFileName().toLowerCase();
            if (!fileName.endsWith("." + fileType.toLowerCase())) {
                return false;
            }
        }

        // 组织标签过滤
        if (orgTag != null && !orgTag.equals(file.getOrgTag())) {
            return false;
        }

        // 公开性过滤
        if (isPublic != null && isPublic != file.isPublic()) {
            return false;
        }

        // 时间范围过滤
        if (dateFrom != null || dateTo != null) {
            LocalDateTime uploadTime = file.getCreatedAt();

            if (dateFrom != null) {
                LocalDateTime fromDate = LocalDateTime.parse(dateFrom + "T00:00:00");
                if (uploadTime.isBefore(fromDate)) {
                    return false;
                }
            }

            if (dateTo != null) {
                LocalDateTime toDate = LocalDateTime.parse(dateTo + "T23:59:59");
                if (uploadTime.isAfter(toDate)) {
                    return false;
                }
            }
        }

        return true;
    }

    /**
     * 格式化文件大小
     */
    private String formatFileSize(long size) {
        if (size < 1024) {
            return size + " B";
        } else if (size < 1024 * 1024) {
            return String.format("%.2f KB", size / 1024.0);
        } else if (size < 1024 * 1024 * 1024) {
            return String.format("%.2f MB", size / (1024.0 * 1024));
        } else {
            return String.format("%.2f GB", size / (1024.0 * 1024 * 1024));
        }
    }

    /**
     * 构建过滤条件描述
     */
    private Map<String, Object> buildFiltersDescription(String fileType, String orgTag,
            Boolean isPublic, String dateFrom, String dateTo) {
        Map<String, Object> filters = new LinkedHashMap<>();
        if (fileType != null)
            filters.put("file_type", fileType);
        if (orgTag != null)
            filters.put("org_tag", orgTag);
        if (isPublic != null)
            filters.put("is_public", isPublic);
        if (dateFrom != null)
            filters.put("date_from", dateFrom);
        if (dateTo != null)
            filters.put("date_to", dateTo);
        return filters;
    }
}
