package com.yizhaoqi.smartpai.tools;

import com.yizhaoqi.smartpai.model.FileUpload;
import com.yizhaoqi.smartpai.model.ToolDefinition;
import com.yizhaoqi.smartpai.model.ToolDefinition.FunctionDefinition;
import com.yizhaoqi.smartpai.model.ToolDefinition.ParametersSchema;
import com.yizhaoqi.smartpai.model.ToolDefinition.PropertyDefinition;
import com.yizhaoqi.smartpai.model.ToolResult;
import com.yizhaoqi.smartpai.service.DocumentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 文档使用统计工具
 * 统计指定时间范围内文档的使用情况（基于 Redis 检索记录）
 * 
 * 注意：此工具统计的是文档被检索的频率，作为"使用"的代理指标
 * 
 * @author Generated by AI Assistant
 */
@Component
public class DocumentUsageStatsTool implements Tool {

    private static final Logger logger = LoggerFactory.getLogger(DocumentUsageStatsTool.class);
    private static final String REDIS_KEY_PREFIX = "doc:access:";

    @Autowired
    private DocumentService documentService;

    @Autowired
    private RedisTemplate<String, String> redisTemplate;

    @Override
    public ToolDefinition getDefinition() {
        Map<String, PropertyDefinition> properties = new LinkedHashMap<>();

        properties.put("time_range", PropertyDefinition.builder()
                .type("string")
                .description("时间范围：'today'(今天), '7d'(最近7天), '30d'(最近30天), '90d'(最近90天)")
                .enumValues(Arrays.asList("today", "7d", "30d", "90d"))
                .defaultValue("7d")
                .build());

        properties.put("top_k", PropertyDefinition.builder()
                .type("integer")
                .description("返回使用最多的前K个文档")
                .defaultValue(10)
                .build());

        properties.put("group_by", PropertyDefinition.builder()
                .type("string")
                .description("分组维度：'file_type'(按文件类型), 'org_tag'(按组织), 'none'(不分组)")
                .enumValues(Arrays.asList("file_type", "org_tag", "none"))
                .defaultValue("none")
                .build());

        return ToolDefinition.builder()
                .type("function")
                .function(FunctionDefinition.builder()
                        .name("document_usage_stats")
                        .description("统计文档使用情况，显示最近一段时间内哪些文档被检索/使用最多。" +
                                "基于文档被检索的频率来衡量使用情况。" +
                                "适用于了解知识库中哪些内容最受关注、最常被查询等场景。")
                        .parameters(ParametersSchema.builder()
                                .type("object")
                                .properties(properties)
                                .build())
                        .build())
                .build();
    }

    @Override
    public ToolResult execute(Map<String, Object> parameters, String userId) {
        long startTime = System.currentTimeMillis();

        try {
            // 提取参数
            String timeRange = (String) parameters.getOrDefault("time_range", "7d");
            Integer topK = parameters.containsKey("top_k") ? ((Number) parameters.get("top_k")).intValue() : 10;
            String groupBy = (String) parameters.getOrDefault("group_by", "none");

            logger.info("执行文档使用统计 - userId: {}, timeRange: {}, topK: {}, groupBy: {}",
                    userId, timeRange, topK, groupBy);

            // 计算时间范围
            LocalDateTime startDate = calculateStartDate(timeRange);

            // 获取用户可访问的所有文档
            List<FileUpload> accessibleFiles = documentService.getAccessibleFiles(userId, null);

            logger.info("用户可访问文档总数: {}", accessibleFiles.size());

            // 获取每个文档的检索次数（从 Redis）
            Map<String, DocumentStats> statsMap = new HashMap<>();
            for (FileUpload file : accessibleFiles) {
                String redisKey = REDIS_KEY_PREFIX + file.getFileMd5();
                String countStr = redisTemplate.opsForValue().get(redisKey);
                int accessCount = countStr != null ? Integer.parseInt(countStr) : 0;

                DocumentStats stats = new DocumentStats();
                stats.fileMd5 = file.getFileMd5();
                stats.fileName = file.getFileName();
                stats.accessCount = accessCount;
                stats.totalSize = file.getTotalSize();
                stats.uploadTime = file.getCreatedAt();
                stats.isPublic = file.isPublic();
                stats.orgTag = file.getOrgTag();
                stats.fileType = extractFileType(file.getFileName());

                statsMap.put(file.getFileMd5(), stats);
            }

            // 根据 group_by 参数处理结果
            Object result;
            if ("file_type".equals(groupBy)) {
                result = groupByFileType(statsMap, topK);
            } else if ("org_tag".equals(groupBy)) {
                result = groupByOrgTag(statsMap, topK);
            } else {
                result = getTopDocuments(statsMap, topK, startDate);
            }

            long executionTime = System.currentTimeMillis() - startTime;

            logger.info("文档使用统计完成，耗时 {}ms", executionTime);

            return ToolResult.success(result, executionTime);

        } catch (Exception e) {
            long executionTime = System.currentTimeMillis() - startTime;
            logger.error("文档使用统计失败", e);
            return ToolResult.failure("统计失败: " + e.getMessage(), executionTime);
        }
    }

    /**
     * 获取使用最多的文档（不分组）
     */
    private Map<String, Object> getTopDocuments(Map<String, DocumentStats> statsMap,
            int topK, LocalDateTime startDate) {
        List<Map<String, Object>> topDocs = statsMap.values().stream()
                .filter(stats -> stats.uploadTime.isAfter(startDate) || stats.accessCount > 0)
                .sorted((a, b) -> Integer.compare(b.accessCount, a.accessCount))
                .limit(topK)
                .map(stats -> {
                    Map<String, Object> doc = new LinkedHashMap<>();
                    doc.put("file_name", stats.fileName);
                    doc.put("file_md5", stats.fileMd5);
                    doc.put("access_count", stats.accessCount);
                    doc.put("file_type", stats.fileType);
                    doc.put("file_size", formatFileSize(stats.totalSize));
                    doc.put("upload_time", stats.uploadTime.toString());
                    doc.put("is_public", stats.isPublic);
                    doc.put("org_tag", stats.orgTag != null ? stats.orgTag : "无");
                    doc.put("days_since_upload", ChronoUnit.DAYS.between(stats.uploadTime, LocalDateTime.now()));
                    return doc;
                })
                .collect(Collectors.toList());

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("summary", String.format("统计期内共有 %d 个文档被访问", topDocs.size()));
        response.put("total_documents", statsMap.size());
        response.put("accessed_documents", topDocs.stream().filter(d -> (int) d.get("access_count") > 0).count());
        response.put("top_documents", topDocs);

        return response;
    }

    /**
     * 按文件类型分组统计
     */
    private Map<String, Object> groupByFileType(Map<String, DocumentStats> statsMap, int topK) {
        Map<String, TypeStats> typeStatsMap = new HashMap<>();

        for (DocumentStats stats : statsMap.values()) {
            typeStatsMap.computeIfAbsent(stats.fileType, k -> new TypeStats())
                    .addDocument(stats);
        }

        List<Map<String, Object>> typeStatsList = typeStatsMap.entrySet().stream()
                .sorted((a, b) -> Integer.compare(b.getValue().totalAccess, a.getValue().totalAccess))
                .limit(topK)
                .map(entry -> {
                    Map<String, Object> typeStat = new LinkedHashMap<>();
                    typeStat.put("file_type", entry.getKey());
                    typeStat.put("document_count", entry.getValue().count);
                    typeStat.put("total_access", entry.getValue().totalAccess);
                    typeStat.put("avg_access_per_doc",
                            entry.getValue().count > 0 ? entry.getValue().totalAccess / entry.getValue().count : 0);
                    return typeStat;
                })
                .collect(Collectors.toList());

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("summary", "按文件类型分组统计");
        response.put("type_stats", typeStatsList);

        return response;
    }

    /**
     * 按组织标签分组统计
     */
    private Map<String, Object> groupByOrgTag(Map<String, DocumentStats> statsMap, int topK) {
        Map<String, TypeStats> orgStatsMap = new HashMap<>();

        for (DocumentStats stats : statsMap.values()) {
            String orgTag = stats.orgTag != null ? stats.orgTag : "无组织";
            orgStatsMap.computeIfAbsent(orgTag, k -> new TypeStats())
                    .addDocument(stats);
        }

        List<Map<String, Object>> orgStatsList = orgStatsMap.entrySet().stream()
                .sorted((a, b) -> Integer.compare(b.getValue().totalAccess, a.getValue().totalAccess))
                .limit(topK)
                .map(entry -> {
                    Map<String, Object> orgStat = new LinkedHashMap<>();
                    orgStat.put("org_tag", entry.getKey());
                    orgStat.put("document_count", entry.getValue().count);
                    orgStat.put("total_access", entry.getValue().totalAccess);
                    orgStat.put("avg_access_per_doc",
                            entry.getValue().count > 0 ? entry.getValue().totalAccess / entry.getValue().count : 0);
                    return orgStat;
                })
                .collect(Collectors.toList());

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("summary", "按组织标签分组统计");
        response.put("org_stats", orgStatsList);

        return response;
    }

    /**
     * 计算开始日期
     */
    private LocalDateTime calculateStartDate(String timeRange) {
        LocalDateTime now = LocalDateTime.now();
        switch (timeRange) {
            case "today":
                return now.truncatedTo(ChronoUnit.DAYS);
            case "7d":
                return now.minusDays(7);
            case "30d":
                return now.minusDays(30);
            case "90d":
                return now.minusDays(90);
            default:
                return now.minusDays(7);
        }
    }

    /**
     * 提取文件类型
     */
    private String extractFileType(String fileName) {
        int lastDot = fileName.lastIndexOf('.');
        if (lastDot > 0 && lastDot < fileName.length() - 1) {
            return fileName.substring(lastDot + 1).toLowerCase();
        }
        return "unknown";
    }

    /**
     * 格式化文件大小
     */
    private String formatFileSize(long size) {
        if (size < 1024) {
            return size + " B";
        } else if (size < 1024 * 1024) {
            return String.format("%.2f KB", size / 1024.0);
        } else if (size < 1024 * 1024 * 1024) {
            return String.format("%.2f MB", size / (1024.0 * 1024));
        } else {
            return String.format("%.2f GB", size / (1024.0 * 1024 * 1024));
        }
    }

    /**
     * 文档统计信息内部类
     */
    private static class DocumentStats {
        String fileMd5;
        String fileName;
        int accessCount;
        long totalSize;
        LocalDateTime uploadTime;
        boolean isPublic;
        String orgTag;
        String fileType;
    }

    /**
     * 类型/组织统计内部类
     */
    private static class TypeStats {
        int count = 0;
        int totalAccess = 0;

        void addDocument(DocumentStats stats) {
            count++;
            totalAccess += stats.accessCount;
        }
    }
}
