package com.yizhaoqi.smartpai.tools;

import com.yizhaoqi.smartpai.model.ToolDefinition;
import com.yizhaoqi.smartpai.model.ToolResult;

import java.util.Map;

/**
 * Function Call 工具接口
 * 所有工具必须实现此接口
 * 
 * @author Generated by AI Assistant
 */
public interface Tool {

    /**
     * 获取工具定义（包含名称、描述、参数 Schema）
     * 
     * @return 工具定义
     */
    ToolDefinition getDefinition();

    /**
     * 执行工具
     * 
     * @param parameters 工具参数
     * @param userId     调用用户ID（用于权限验证）
     * @return 执行结果
     */
    ToolResult execute(Map<String, Object> parameters, String userId);

    /**
     * 获取工具名称
     * 
     * @return 工具名称
     */
    default String getName() {
        return getDefinition().getFunction().getName();
    }
}
