package com.yizhaoqi.smartpai.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 工具执行结果
 * 
 * @author Generated by AI Assistant
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ToolResult {

    /**
     * 是否执行成功
     */
    private boolean success;

    /**
     * 执行结果数据
     */
    private Object data;

    /**
     * 错误信息（失败时）
     */
    private String error;

    /**
     * 执行耗时（毫秒）
     */
    private long executionTimeMs;

    /**
     * 创建成功结果
     */
    public static ToolResult success(Object data) {
        return ToolResult.builder()
                .success(true)
                .data(data)
                .build();
    }

    /**
     * 创建成功结果（带执行时间）
     */
    public static ToolResult success(Object data, long executionTimeMs) {
        return ToolResult.builder()
                .success(true)
                .data(data)
                .executionTimeMs(executionTimeMs)
                .build();
    }

    /**
     * 创建失败结果
     */
    public static ToolResult failure(String error) {
        return ToolResult.builder()
                .success(false)
                .error(error)
                .build();
    }

    /**
     * 创建失败结果（带执行时间）
     */
    public static ToolResult failure(String error, long executionTimeMs) {
        return ToolResult.builder()
                .success(false)
                .error(error)
                .executionTimeMs(executionTimeMs)
                .build();
    }
}
