package com.yizhaoqi.smartpai.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Function Call 工具定义
 * 描述工具的名称、功能和参数 Schema
 * 
 * @author Generated by AI Assistant
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ToolDefinition {

    /**
     * 工具类型，固定为 "function"
     */
    @Builder.Default
    private String type = "function";

    /**
     * 工具函数定义
     */
    private FunctionDefinition function;

    /**
     * 函数定义内部类
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FunctionDefinition {
        /**
         * 工具名称（唯一标识符）
         * 例如: "advanced_document_search"
         */
        private String name;

        /**
         * 工具描述（帮助大模型理解何时使用该工具）
         */
        private String description;

        /**
         * 参数 Schema（JSON Schema 格式）
         */
        private ParametersSchema parameters;
    }

    /**
     * 参数 Schema 定义
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ParametersSchema {
        /**
         * 类型，通常为 "object"
         */
        @Builder.Default
        private String type = "object";

        /**
         * 属性定义（参数列表）
         * Key: 参数名, Value: 参数定义
         */
        private Map<String, PropertyDefinition> properties;

        /**
         * 必需参数列表
         */
        private List<String> required;
    }

    /**
     * 单个参数的定义
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PropertyDefinition {
        /**
         * 参数类型: string, number, boolean, integer, array, object
         */
        private String type;

        /**
         * 参数描述
         */
        private String description;

        /**
         * 枚举值（可选）
         */
        private List<String> enumValues;

        /**
         * 默认值（可选）
         */
        private Object defaultValue;

        /**
         * 数组元素类型（type=array 时）
         */
        private PropertyDefinition items;
    }
}
